import { Mongo } from 'meteor/mongo';

export const NewsPosts = new Mongo.Collection('newsPosts');
export const Matches = new Mongo.Collection('matches')
export const Resolutions = new Mongo.Collection('resolutions');
export const Tweets = new Mongo.Collection('tweets');
export const TwitchNames = new Mongo.Collection('twitchNames');
export const Streams = new Mongo.Collection('streams');
export const Shouts = new Mongo.Collection('shouts');
export const Players = new Mongo.Collection('players');
export const PlayerStats = new Mongo.Collection('playerStats');
export const Media = new Mongo.Collection('media');
export const Schedule = new Mongo.Collection('schedule');
export const ForumCategories = new Mongo.Collection('foremCategories');
export const ForumThreads = new Mongo.Collection('forumThreads');
export const ForumPosts = new Mongo.Collection('forumPosts');
export const ChatMessages = new Mongo.Collection('chatMessages');
export const ImgurTokens = new Mongo.Collection('imgurTokens');
export const ClubInfos = new Mongo.Collection('clubInfo');
export const DeletedUsers = new Mongo.Collection('deletedUsers');
export const SharedSettings = new Mongo.Collection('sharedSettings');
